-- ============================================================
-- 07. CAMADA ANALITICA DO SELECT AI DO SITE · rodar conectado como ADMIN (F5)
-- Cria views AGREGADAS (nenhum dado individual) com nomes e comentarios em portugues,
-- para a IA responder evolucao, ultimos meses, demanda x oferta e rankings sem erro.
-- O usuario do site (PRAZO60_APP) passa a enxergar SOMENTE estas views.
-- Considera os 45.416 casos da carga completa (os 200 casos da Sprint 3 nao tem residencia).
-- Pode rodar mais de uma vez. Leva menos de 1 minuto.
-- ============================================================
SET DEFINE OFF

-- 0. Trava: se nao estiver como ADMIN, para aqui sem executar nada
WHENEVER SQLERROR EXIT ROLLBACK
BEGIN
  IF USER <> 'ADMIN' THEN
    RAISE_APPLICATION_ERROR(-20001, 'Rode este script na conexao PRAZO60_EDUARDO (ADMIN). Conectado agora como: ' || USER);
  END IF;
END;
/
WHENEVER SQLERROR CONTINUE

-- 1. Oferta habilitada por DRS e ano (Painel-Oncologia, indicadores territoriais)
BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE ADMIN.TB_OFERTA_DRS (COD_DRS VARCHAR2(10), ANO NUMBER(4), '
    || 'ESTABELECIMENTOS_CACON_UNACON NUMBER, MAMOGRAFIAS_RASTREIO NUMBER, '
    || 'CONSTRAINT PK_OFERTA_DRS PRIMARY KEY (COD_DRS, ANO))';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE <> -955 THEN RAISE; END IF;
END;
/

MERGE INTO ADMIN.TB_OFERTA_DRS t
USING (
  SELECT 'DRS-01' AS COD_DRS, 2022 AS ANO, 24 AS ESTAB, 434160 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-01' AS COD_DRS, 2023 AS ANO, 25 AS ESTAB, 419710 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-01' AS COD_DRS, 2024 AS ANO, 25 AS ESTAB, 421528 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-01' AS COD_DRS, 2025 AS ANO, 27 AS ESTAB, 449046 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-01' AS COD_DRS, 2026 AS ANO, 27 AS ESTAB, 231436 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-02' AS COD_DRS, 2022 AS ANO, 1 AS ESTAB, 10112 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-02' AS COD_DRS, 2023 AS ANO, 1 AS ESTAB, 10860 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-02' AS COD_DRS, 2024 AS ANO, 1 AS ESTAB, 10218 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-02' AS COD_DRS, 2025 AS ANO, 1 AS ESTAB, 10978 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-02' AS COD_DRS, 2026 AS ANO, 1 AS ESTAB, 5272 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-03' AS COD_DRS, 2022 AS ANO, 2 AS ESTAB, 16445 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-03' AS COD_DRS, 2023 AS ANO, 2 AS ESTAB, 18845 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-03' AS COD_DRS, 2024 AS ANO, 2 AS ESTAB, 17698 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-03' AS COD_DRS, 2025 AS ANO, 2 AS ESTAB, 17285 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-03' AS COD_DRS, 2026 AS ANO, 2 AS ESTAB, 8145 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-04' AS COD_DRS, 2022 AS ANO, 4 AS ESTAB, 35882 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-04' AS COD_DRS, 2023 AS ANO, 4 AS ESTAB, 38073 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-04' AS COD_DRS, 2024 AS ANO, 4 AS ESTAB, 36212 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-04' AS COD_DRS, 2025 AS ANO, 4 AS ESTAB, 33304 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-04' AS COD_DRS, 2026 AS ANO, 4 AS ESTAB, 17922 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-05' AS COD_DRS, 2022 AS ANO, 1 AS ESTAB, 49357 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-05' AS COD_DRS, 2023 AS ANO, 1 AS ESTAB, 42631 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-05' AS COD_DRS, 2024 AS ANO, 1 AS ESTAB, 41269 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-05' AS COD_DRS, 2025 AS ANO, 1 AS ESTAB, 40442 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-05' AS COD_DRS, 2026 AS ANO, 1 AS ESTAB, 20708 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-06' AS COD_DRS, 2022 AS ANO, 4 AS ESTAB, 24386 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-06' AS COD_DRS, 2023 AS ANO, 4 AS ESTAB, 24148 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-06' AS COD_DRS, 2024 AS ANO, 4 AS ESTAB, 28437 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-06' AS COD_DRS, 2025 AS ANO, 4 AS ESTAB, 29583 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-06' AS COD_DRS, 2026 AS ANO, 4 AS ESTAB, 16348 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-07' AS COD_DRS, 2022 AS ANO, 7 AS ESTAB, 76149 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-07' AS COD_DRS, 2023 AS ANO, 9 AS ESTAB, 73928 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-07' AS COD_DRS, 2024 AS ANO, 9 AS ESTAB, 76130 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-07' AS COD_DRS, 2025 AS ANO, 10 AS ESTAB, 70516 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-07' AS COD_DRS, 2026 AS ANO, 10 AS ESTAB, 33890 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-08' AS COD_DRS, 2022 AS ANO, 1 AS ESTAB, 13551 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-08' AS COD_DRS, 2023 AS ANO, 1 AS ESTAB, 13177 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-08' AS COD_DRS, 2024 AS ANO, 1 AS ESTAB, 13182 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-08' AS COD_DRS, 2025 AS ANO, 1 AS ESTAB, 13681 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-08' AS COD_DRS, 2026 AS ANO, 1 AS ESTAB, 7751 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-09' AS COD_DRS, 2022 AS ANO, 5 AS ESTAB, 21322 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-09' AS COD_DRS, 2023 AS ANO, 5 AS ESTAB, 22837 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-09' AS COD_DRS, 2024 AS ANO, 5 AS ESTAB, 23552 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-09' AS COD_DRS, 2025 AS ANO, 5 AS ESTAB, 22199 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-09' AS COD_DRS, 2026 AS ANO, 6 AS ESTAB, 12008 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-10' AS COD_DRS, 2022 AS ANO, 5 AS ESTAB, 21141 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-10' AS COD_DRS, 2023 AS ANO, 5 AS ESTAB, 24523 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-10' AS COD_DRS, 2024 AS ANO, 5 AS ESTAB, 24616 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-10' AS COD_DRS, 2025 AS ANO, 5 AS ESTAB, 26294 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-10' AS COD_DRS, 2026 AS ANO, 5 AS ESTAB, 13464 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-11' AS COD_DRS, 2022 AS ANO, 2 AS ESTAB, 14544 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-11' AS COD_DRS, 2023 AS ANO, 2 AS ESTAB, 15543 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-11' AS COD_DRS, 2024 AS ANO, 2 AS ESTAB, 15570 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-11' AS COD_DRS, 2025 AS ANO, 2 AS ESTAB, 15797 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-11' AS COD_DRS, 2026 AS ANO, 2 AS ESTAB, 10845 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-12' AS COD_DRS, 2022 AS ANO, 1 AS ESTAB, 4769 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-12' AS COD_DRS, 2023 AS ANO, 1 AS ESTAB, 4445 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-12' AS COD_DRS, 2024 AS ANO, 1 AS ESTAB, 5368 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-12' AS COD_DRS, 2025 AS ANO, 1 AS ESTAB, 4850 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-12' AS COD_DRS, 2026 AS ANO, 1 AS ESTAB, 3051 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-13' AS COD_DRS, 2022 AS ANO, 3 AS ESTAB, 18926 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-13' AS COD_DRS, 2023 AS ANO, 3 AS ESTAB, 20432 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-13' AS COD_DRS, 2024 AS ANO, 3 AS ESTAB, 19897 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-13' AS COD_DRS, 2025 AS ANO, 3 AS ESTAB, 22423 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-13' AS COD_DRS, 2026 AS ANO, 3 AS ESTAB, 11731 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-14' AS COD_DRS, 2022 AS ANO, 2 AS ESTAB, 14332 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-14' AS COD_DRS, 2023 AS ANO, 2 AS ESTAB, 15028 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-14' AS COD_DRS, 2024 AS ANO, 2 AS ESTAB, 15984 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-14' AS COD_DRS, 2025 AS ANO, 2 AS ESTAB, 15889 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-14' AS COD_DRS, 2026 AS ANO, 2 AS ESTAB, 8250 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-15' AS COD_DRS, 2022 AS ANO, 4 AS ESTAB, 43074 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-15' AS COD_DRS, 2023 AS ANO, 4 AS ESTAB, 45483 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-15' AS COD_DRS, 2024 AS ANO, 4 AS ESTAB, 44237 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-15' AS COD_DRS, 2025 AS ANO, 4 AS ESTAB, 38968 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-15' AS COD_DRS, 2026 AS ANO, 4 AS ESTAB, 17527 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-16' AS COD_DRS, 2022 AS ANO, 4 AS ESTAB, 31675 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-16' AS COD_DRS, 2023 AS ANO, 4 AS ESTAB, 29825 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-16' AS COD_DRS, 2024 AS ANO, 4 AS ESTAB, 35894 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-16' AS COD_DRS, 2025 AS ANO, 4 AS ESTAB, 32550 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-16' AS COD_DRS, 2026 AS ANO, 4 AS ESTAB, 16757 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-17' AS COD_DRS, 2022 AS ANO, 7 AS ESTAB, 53437 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-17' AS COD_DRS, 2023 AS ANO, 6 AS ESTAB, 53690 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-17' AS COD_DRS, 2024 AS ANO, 7 AS ESTAB, 53574 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-17' AS COD_DRS, 2025 AS ANO, 7 AS ESTAB, 53890 AS MAMO FROM dual
  UNION ALL
  SELECT 'DRS-17' AS COD_DRS, 2026 AS ANO, 7 AS ESTAB, 29716 AS MAMO FROM dual
) s ON (t.COD_DRS = s.COD_DRS AND t.ANO = s.ANO)
WHEN MATCHED THEN UPDATE SET t.ESTABELECIMENTOS_CACON_UNACON = s.ESTAB, t.MAMOGRAFIAS_RASTREIO = s.MAMO
WHEN NOT MATCHED THEN INSERT (COD_DRS, ANO, ESTABELECIMENTOS_CACON_UNACON, MAMOGRAFIAS_RASTREIO)
VALUES (s.COD_DRS, s.ANO, s.ESTAB, s.MAMO);
COMMIT;

-- 2. Base interna (nivel caso). NAO e liberada para o usuario do site.
CREATE OR REPLACE VIEW ADMIN.VW_P60_BASE AS
SELECT c.ID_CASO,
       EXTRACT(YEAR FROM c.DATA_DIAGNOSTICO)  AS ANO,
       EXTRACT(MONTH FROM c.DATA_DIAGNOSTICO) AS MES,
       t.DIAS_ESPERA,
       CASE WHEN t.DIAS_ESPERA > 60 THEN 1 ELSE 0 END AS ACIMA_60,
       d.COD_DRS, d.NOME_DRS, m.NOME_MUNICIPIO,
       u.COD_CNES, u.NOME_UNIDADE,
       mu.NOME_MUNICIPIO AS MUNICIPIO_UNIDADE, du.COD_DRS AS COD_DRS_UNIDADE, du.NOME_DRS AS DRS_UNIDADE,
       tt.NOME_TIPO_TRATAMENTO
FROM ADMIN.TB_CASO_PACIENTE c
JOIN ADMIN.TB_TRATAMENTO t       ON t.ID_CASO = c.ID_CASO
JOIN ADMIN.TB_MUNICIPIO m        ON m.ID_MUNICIPIO = c.ID_MUNICIPIO_RESIDENCIA
JOIN ADMIN.TB_DRS d              ON d.ID_DRS = m.ID_DRS
JOIN ADMIN.TB_UNIDADE_SAUDE u    ON u.ID_UNIDADE = t.ID_UNIDADE_TRATAMENTO
JOIN ADMIN.TB_MUNICIPIO mu       ON mu.ID_MUNICIPIO = u.ID_MUNICIPIO
JOIN ADMIN.TB_DRS du             ON du.ID_DRS = mu.ID_DRS
JOIN ADMIN.TB_TIPO_TRATAMENTO tt ON tt.ID_TIPO_TRATAMENTO = t.ID_TIPO_TRATAMENTO;

-- 3. Views agregadas para a IA
CREATE OR REPLACE VIEW ADMIN.VW_P60_RESUMO_ANO AS
SELECT ANO,
       CASE WHEN ANO = (SELECT MAX(ANO) FROM ADMIN.VW_P60_BASE) THEN 'SIM' ELSE 'NAO' END AS ANO_PARCIAL,
       COUNT(*) AS CASOS,
       SUM(ACIMA_60) AS CASOS_ACIMA_60,
       ROUND(100 * AVG(ACIMA_60), 1) AS PCT_ACIMA_60,
       ROUND(AVG(DIAS_ESPERA), 1) AS MEDIA_DIAS,
       MEDIAN(DIAS_ESPERA) AS MEDIANA_DIAS
FROM ADMIN.VW_P60_BASE
GROUP BY ANO;

CREATE OR REPLACE VIEW ADMIN.VW_P60_RESUMO_MES AS
SELECT ANO, MES, TO_CHAR(ANO) || '-' || LPAD(MES, 2, '0') AS ANO_MES,
       COUNT(*) AS CASOS,
       SUM(ACIMA_60) AS CASOS_ACIMA_60,
       ROUND(100 * AVG(ACIMA_60), 1) AS PCT_ACIMA_60,
       ROUND(AVG(DIAS_ESPERA), 1) AS MEDIA_DIAS,
       MEDIAN(DIAS_ESPERA) AS MEDIANA_DIAS
FROM ADMIN.VW_P60_BASE
GROUP BY ANO, MES;

CREATE OR REPLACE VIEW ADMIN.VW_P60_DRS_ANO AS
SELECT COD_DRS, NOME_DRS, ANO,
       COUNT(*) AS CASOS,
       SUM(ACIMA_60) AS CASOS_ACIMA_60,
       ROUND(100 * AVG(ACIMA_60), 1) AS PCT_ACIMA_60,
       ROUND(AVG(DIAS_ESPERA), 1) AS MEDIA_DIAS,
       MEDIAN(DIAS_ESPERA) AS MEDIANA_DIAS
FROM ADMIN.VW_P60_BASE
GROUP BY COD_DRS, NOME_DRS, ANO;

CREATE OR REPLACE VIEW ADMIN.VW_P60_DRS AS
SELECT b.COD_DRS, b.NOME_DRS,
       COUNT(*) AS CASOS,
       SUM(b.ACIMA_60) AS CASOS_ACIMA_60,
       ROUND(100 * AVG(b.ACIMA_60), 1) AS PCT_ACIMA_60,
       ROUND(AVG(b.DIAS_ESPERA), 1) AS MEDIA_DIAS,
       MEDIAN(b.DIAS_ESPERA) AS MEDIANA_DIAS,
       ROUND(100 * AVG(CASE WHEN b.ANO = 2024 THEN b.ACIMA_60 END), 1) AS PCT_ACIMA_60_2024,
       ROUND(100 * AVG(CASE WHEN b.ANO = 2025 THEN b.ACIMA_60 END), 1) AS PCT_ACIMA_60_2025,
       ROUND(100 * AVG(CASE WHEN b.ANO = 2025 THEN b.ACIMA_60 END), 1)
         - ROUND(100 * AVG(CASE WHEN b.ANO = 2024 THEN b.ACIMA_60 END), 1) AS VARIACAO_PP_2024_2025,
       SUM(CASE WHEN b.ANO = 2025 THEN 1 ELSE 0 END) AS CASOS_2025,
       MAX(o.ESTABELECIMENTOS_CACON_UNACON) AS ESTABELECIMENTOS_2025,
       MAX(o.MAMOGRAFIAS_RASTREIO) AS MAMOGRAFIAS_2025,
       ROUND(SUM(CASE WHEN b.ANO = 2025 THEN 1 ELSE 0 END) / NULLIF(MAX(o.ESTABELECIMENTOS_CACON_UNACON), 0), 1) AS PRESSAO_CASOS_POR_ESTABELECIMENTO
FROM ADMIN.VW_P60_BASE b
LEFT JOIN ADMIN.TB_OFERTA_DRS o ON o.COD_DRS = b.COD_DRS AND o.ANO = 2025
GROUP BY b.COD_DRS, b.NOME_DRS;

CREATE OR REPLACE VIEW ADMIN.VW_P60_MUNICIPIO AS
SELECT NOME_MUNICIPIO, COD_DRS, NOME_DRS,
       COUNT(*) AS CASOS,
       SUM(ACIMA_60) AS CASOS_ACIMA_60,
       ROUND(100 * AVG(ACIMA_60), 1) AS PCT_ACIMA_60,
       ROUND(AVG(DIAS_ESPERA), 1) AS MEDIA_DIAS,
       MEDIAN(DIAS_ESPERA) AS MEDIANA_DIAS
FROM ADMIN.VW_P60_BASE
WHERE NOME_MUNICIPIO <> 'Fora do Estado de SP'
GROUP BY NOME_MUNICIPIO, COD_DRS, NOME_DRS
HAVING COUNT(*) >= 30;

CREATE OR REPLACE VIEW ADMIN.VW_P60_UNIDADE AS
SELECT COD_CNES, NOME_UNIDADE, MUNICIPIO_UNIDADE AS NOME_MUNICIPIO, COD_DRS_UNIDADE AS COD_DRS, DRS_UNIDADE AS NOME_DRS,
       COUNT(*) AS CASOS,
       SUM(ACIMA_60) AS CASOS_ACIMA_60,
       ROUND(100 * AVG(ACIMA_60), 1) AS PCT_ACIMA_60,
       ROUND(AVG(DIAS_ESPERA), 1) AS MEDIA_DIAS,
       MEDIAN(DIAS_ESPERA) AS MEDIANA_DIAS
FROM ADMIN.VW_P60_BASE
GROUP BY COD_CNES, NOME_UNIDADE, MUNICIPIO_UNIDADE, COD_DRS_UNIDADE, DRS_UNIDADE
HAVING COUNT(*) >= 30;

CREATE OR REPLACE VIEW ADMIN.VW_P60_TIPO_TRATAMENTO AS
SELECT NOME_TIPO_TRATAMENTO AS TIPO_TRATAMENTO,
       COUNT(*) AS CASOS,
       SUM(ACIMA_60) AS CASOS_ACIMA_60,
       ROUND(100 * AVG(ACIMA_60), 1) AS PCT_ACIMA_60,
       ROUND(AVG(DIAS_ESPERA), 1) AS MEDIA_DIAS,
       MEDIAN(DIAS_ESPERA) AS MEDIANA_DIAS
FROM ADMIN.VW_P60_BASE
GROUP BY NOME_TIPO_TRATAMENTO;

CREATE OR REPLACE VIEW ADMIN.VW_P60_FAIXA_DIAS AS
SELECT FAIXA, ORDEM, COUNT(*) AS CASOS, ROUND(100 * RATIO_TO_REPORT(COUNT(*)) OVER (), 1) AS PCT_DO_TOTAL
FROM (SELECT CASE WHEN DIAS_ESPERA <= 30 THEN '0-30' WHEN DIAS_ESPERA <= 45 THEN '31-45'
                  WHEN DIAS_ESPERA <= 60 THEN '46-60' WHEN DIAS_ESPERA <= 90 THEN '61-90'
                  WHEN DIAS_ESPERA <= 120 THEN '91-120' ELSE '121+' END AS FAIXA,
             CASE WHEN DIAS_ESPERA <= 30 THEN 1 WHEN DIAS_ESPERA <= 45 THEN 2 WHEN DIAS_ESPERA <= 60 THEN 3
                  WHEN DIAS_ESPERA <= 90 THEN 4 WHEN DIAS_ESPERA <= 120 THEN 5 ELSE 6 END AS ORDEM
      FROM ADMIN.VW_P60_BASE)
GROUP BY FAIXA, ORDEM;

-- 4. Comentarios: a IA le estes textos para entender cada view
COMMENT ON TABLE ADMIN.VW_P60_RESUMO_ANO IS 'Indicadores do Estado de SP por ano de diagnostico (cancer de mama). ANO_PARCIAL=SIM indica ano incompleto (2026).';
COMMENT ON TABLE ADMIN.VW_P60_RESUMO_MES IS 'Indicadores do Estado de SP por mes de diagnostico. Para ultimos meses ordene por ANO_MES decrescente.';
COMMENT ON TABLE ADMIN.VW_P60_DRS_ANO IS 'Indicadores por regiao de saude (DRS) de residencia e ano de diagnostico. Use para evolucao ao longo dos anos.';
COMMENT ON TABLE ADMIN.VW_P60_DRS IS 'Indicadores por regiao de saude (DRS) de residencia: totais, evolucao 2024-2025, oferta habilitada 2025 e pressao assistencial.';
COMMENT ON TABLE ADMIN.VW_P60_MUNICIPIO IS 'Indicadores por municipio de residencia, somente municipios com 30 casos ou mais.';
COMMENT ON TABLE ADMIN.VW_P60_UNIDADE IS 'Indicadores por unidade de saude que iniciou o tratamento, somente unidades com 30 casos ou mais.';
COMMENT ON TABLE ADMIN.VW_P60_TIPO_TRATAMENTO IS 'Indicadores por tipo do primeiro tratamento.';
COMMENT ON TABLE ADMIN.VW_P60_FAIXA_DIAS IS 'Distribuicao dos casos por faixa de dias entre diagnostico e inicio do tratamento.';
COMMENT ON COLUMN ADMIN.VW_P60_DRS.PCT_ACIMA_60 IS 'Percentual de casos que iniciaram tratamento apos 60 dias do diagnostico (descumprimento da Lei 12.732/2012).';
COMMENT ON COLUMN ADMIN.VW_P60_DRS.VARIACAO_PP_2024_2025 IS 'Pontos percentuais: PCT_ACIMA_60_2025 menos PCT_ACIMA_60_2024. Positivo = piora, negativo = melhora.';
COMMENT ON COLUMN ADMIN.VW_P60_DRS.PRESSAO_CASOS_POR_ESTABELECIMENTO IS 'Casos de 2025 divididos pelos estabelecimentos habilitados CACON/UNACON de 2025 (demanda x oferta). Maior = mais pressao. Nao indica vaga.';
COMMENT ON COLUMN ADMIN.VW_P60_DRS.ESTABELECIMENTOS_2025 IS 'Estabelecimentos habilitados em oncologia (CACON/UNACON) na DRS em 2025 (oferta).';
COMMENT ON COLUMN ADMIN.VW_P60_RESUMO_MES.ANO_MES IS 'Ano e mes do diagnostico no formato AAAA-MM.';

-- 5. Usuario do site: libera as views agregadas e retira o acesso as tabelas de nivel caso
BEGIN
  FOR v IN (SELECT column_value AS nome FROM TABLE(SYS.ODCIVARCHAR2LIST(
              'VW_P60_RESUMO_ANO', 'VW_P60_RESUMO_MES', 'VW_P60_DRS', 'VW_P60_DRS_ANO',
              'VW_P60_MUNICIPIO', 'VW_P60_UNIDADE', 'VW_P60_TIPO_TRATAMENTO', 'VW_P60_FAIXA_DIAS'))) LOOP
    EXECUTE IMMEDIATE 'GRANT SELECT ON ADMIN.' || v.nome || ' TO PRAZO60_APP';
  END LOOP;
  FOR t IN (SELECT column_value AS nome FROM TABLE(SYS.ODCIVARCHAR2LIST(
              'VW_CASO_PACIENTE', 'TB_TRATAMENTO', 'TB_UNIDADE_SAUDE', 'TB_MUNICIPIO',
              'TB_DRS', 'TB_STATUS_PRAZO', 'TB_TIPO_TRATAMENTO'))) LOOP
    BEGIN
      EXECUTE IMMEDIATE 'REVOKE SELECT ON ADMIN.' || t.nome || ' FROM PRAZO60_APP';
    EXCEPTION WHEN OTHERS THEN NULL;
    END;
  END LOOP;
END;
/

-- 6. Conferencia. Esperado: 45416 casos e 27830 acima de 60 dias (mesmos numeros do site)
SELECT SUM(CASOS) AS CASOS, SUM(CASOS_ACIMA_60) AS CASOS_ACIMA_60 FROM ADMIN.VW_P60_RESUMO_ANO;

-- Esperado no topo: DRS XII - Registro com +10,4
SELECT NOME_DRS, PCT_ACIMA_60_2024, PCT_ACIMA_60_2025, VARIACAO_PP_2024_2025, PRESSAO_CASOS_POR_ESTABELECIMENTO
FROM ADMIN.VW_P60_DRS
ORDER BY VARIACAO_PP_2024_2025 DESC NULLS LAST
FETCH FIRST 3 ROWS ONLY;
